# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
- id: pop_darwin
  goos:
    - darwin
  goarch:
    - amd64
    - 386
  env:
    - CGO_ENABLED=0

- id: pop_linux
  goos:
    - linux
  goarch:
    - amd64
    - 386
  env:
    - CGO_ENABLED=0

- id: windows
  goos:
    - windows
  goarch:
    - amd64
    - 386
  env:
    - CGO_ENABLED=0
  ldflags:
    - -H windowsgui

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - tpl/**/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
