// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {builder} from '../models';

export function CreateProvider(arg1:config.Config):Promise<{[key: string]: any}>;

export function Custom(arg1:number,arg2:string,arg3:any):Promise<{[key: string]: any}>;

export function Error(arg1:string):Promise<{[key: string]: any}>;

export function Generate(arg1:builder.GenerateRequest):Promise<{[key: string]: any}>;

export function GetConfig():Promise<{[key: string]: any}>;

export function GetGenerateColumns(arg1:builder.GetGenerateColumnRequest):Promise<{[key: string]: any}>;

export function GetTables():Promise<{[key: string]: any}>;

export function GetTemplates():Promise<{[key: string]: any}>;

export function HasProvider():Promise<{[key: string]: any}>;

export function Ok(arg1:any):Promise<{[key: string]: any}>;
