// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProvider(arg1) {
  return window['go']['app']['Application']['CreateProvider'](arg1);
}

export function Custom(arg1, arg2, arg3) {
  return window['go']['app']['Application']['Custom'](arg1, arg2, arg3);
}

export function Error(arg1) {
  return window['go']['app']['Application']['Error'](arg1);
}

export function Generate(arg1) {
  return window['go']['app']['Application']['Generate'](arg1);
}

export function GetConfig() {
  return window['go']['app']['Application']['GetConfig']();
}

export function GetGenerateColumns(arg1) {
  return window['go']['app']['Application']['GetGenerateColumns'](arg1);
}

export function GetTables() {
  return window['go']['app']['Application']['GetTables']();
}

export function GetTemplates() {
  return window['go']['app']['Application']['GetTemplates']();
}

export function HasProvider() {
  return window['go']['app']['Application']['HasProvider']();
}

export function Ok(arg1) {
  return window['go']['app']['Application']['Ok'](arg1);
}
